/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoriesRouteImport } from './routes/theories'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AllowedRouteImport } from './routes/allowed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TheoriesRoute = TheoriesRouteImport.update({
  id: '/theories',
  path: '/theories',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AllowedRoute = AllowedRouteImport.update({
  id: '/allowed',
  path: '/allowed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allowed': typeof AllowedRoute
  '/faq': typeof FaqRoute
  '/forbidden': typeof ForbiddenRoute
  '/theories': typeof TheoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allowed': typeof AllowedRoute
  '/faq': typeof FaqRoute
  '/forbidden': typeof ForbiddenRoute
  '/theories': typeof TheoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allowed': typeof AllowedRoute
  '/faq': typeof FaqRoute
  '/forbidden': typeof ForbiddenRoute
  '/theories': typeof TheoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/allowed' | '/faq' | '/forbidden' | '/theories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/allowed' | '/faq' | '/forbidden' | '/theories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/allowed'
    | '/faq'
    | '/forbidden'
    | '/theories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AllowedRoute: typeof AllowedRoute
  FaqRoute: typeof FaqRoute
  ForbiddenRoute: typeof ForbiddenRoute
  TheoriesRoute: typeof TheoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theories': {
      id: '/theories'
      path: '/theories'
      fullPath: '/theories'
      preLoaderRoute: typeof TheoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allowed': {
      id: '/allowed'
      path: '/allowed'
      fullPath: '/allowed'
      preLoaderRoute: typeof AllowedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AllowedRoute: AllowedRoute,
  FaqRoute: FaqRoute,
  ForbiddenRoute: ForbiddenRoute,
  TheoriesRoute: TheoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
